image: busybox

pages:
  stage: deploy
  environment: production
  script:
    - mkdir .public
    - cp -r src/web/* .public
    - mv .public public
    - echo "The site will be deployed to $CI_PAGES_URL"
  artifacts:
    paths:
      - public
  only:
    - main
